import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PDVLayoutSwing {
    private double totalVenda;
    private JTextArea display;

    public PDVLayoutSwing() {
        totalVenda = 0.0;

        // Criação da janela principal
        JFrame frame = new JFrame("PDV - Ponto de Venda");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300);

        // Painel principal
        JPanel panel = new JPanel(new BorderLayout());

        // Área de exibição para mostrar produtos e total da venda
        display = new JTextArea(10, 20);
        display.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(display);
        panel.add(scrollPane, BorderLayout.CENTER);

        // Painel para os botões
        JPanel buttonPanel = new JPanel(new GridLayout(2, 1));

        // Botão para adicionar produto
        JButton addProductButton = new JButton("Adicionar Produto");
        addProductButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String input = JOptionPane.showInputDialog(frame, "Digite o valor do produto:");
                try {
                    double price = Double.parseDouble(input);
                    totalVenda += price;
                    display.append("Produto adicionado: R$" + price + "\n");
                    display.append("Total da venda: R$" + totalVenda + "\n\n");
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(frame, "Valor inválido! Digite um número válido.");
                }
            }
        });

        // Botão para finalizar a venda
        JButton finalizeButton = new JButton("Finalizar Venda");
        finalizeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(frame, "Venda finalizada. Total a pagar: R$" + totalVenda);
                totalVenda = 0.0;
                display.setText("");
            }
        });

        // Adiciona os botões ao painel de botões
        buttonPanel.add(addProductButton);
        buttonPanel.add(finalizeButton);

        // Adiciona o painel de botões ao painel principal
        panel.add(buttonPanel, BorderLayout.SOUTH);

        // Adiciona o painel principal à janela
        frame.add(panel);
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        // Executa o PDV
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new PDVLayoutSwing();
            }
        });
    }
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the edito

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

