import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PDVSwing {
    private double totalVenda;
    private JTextArea display;

    public PDVSwing() {
        totalVenda = 0.0;

        // Configuração da janela principal
        JFrame frame = new JFrame("PDV - Ponto de Venda");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300);

        // Painel principal
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());

        // Área de exibição para mostrar o total da venda
        display = new JTextArea(10, 20);
        display.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(display);
        panel.add(scrollPane, BorderLayout.CENTER);

        // Botões para adicionar produtos e finalizar a venda
        JButton addProductButton = new JButton("Adicionar Produto");
        JButton finalizeButton = new JButton("Finalizar Venda");

        // Adiciona ações aos botões
        addProductButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String input = JOptionPane.showInputDialog(frame, "Digite o valor do produto:");
                try {
                    double price = Double.parseDouble(input);
                    totalVenda += price;
                    display.append("Produto adicionado: R$" + price + "\n");
                    display.append("Total da venda: R$" + totalVenda + "\n\n");
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(frame, "Valor inválido! Digite um número válido.");
                }
            }
        });

        finalizeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(frame, "Venda finalizada. Total a pagar: R$" + totalVenda);
                totalVenda = 0.0;
                display.setText("");
            }
        });

        // Painel para os botões
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(addProductButton);
        buttonPanel.add(finalizeButton);

        panel.add(buttonPanel, BorderLayout.SOUTH);

        // Adiciona o painel principal à janela
        frame.add(panel);
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        // Executa o PDV
        SwingUtilities.invokeLater(() -> {
            new PDVSwing();
        });
    }
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Colorindo Festas
 */
public class PdvSwing extends javax.swing.JFrame {

    /**
     * Creates new form PdvSuzy
     */
    public PdvSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PdvSuzy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PdvSwing().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private static class PdvSuzy {

        public PdvSuzy() {
        }
    }
}
